# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-13 10:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_resourceNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(max_length=1000, unique=True)),
                ('etag', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='User_tokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('crmuserid', models.CharField(max_length=20, unique=True)),
                ('refresh_token', models.CharField(max_length=1000)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('state_key', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='user_resourcenames',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User_tokens'),
        ),
    ]
