# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-07 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_tokens',
            name='crmuserid',
            field=models.CharField(max_length=20),
        ),
    ]
