# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-23 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191007_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_tokens',
            name='refresh_token',
            field=models.CharField(max_length=1000),
        ),
    ]
