# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-04 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_user_resourcenames'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_resourcenames',
            name='etag',
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='user_resourcenames',
            name='resource_name',
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='user_tokens',
            name='crmuserid',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user_tokens',
            name='refresh_token',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
