# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-04 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20191104_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_resourcenames',
            name='etag',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='user_tokens',
            name='refresh_token',
            field=models.CharField(max_length=1000),
        ),
    ]
